networks:
  rpi4b-network:
    name: rpi4b-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  mysql-network:
    driver: bridge
    name: mysql-network
    ipam:
      config:
        - subnet: 172.21.0.0/24

include:
  # PREFIX dns = DNS / AdBlock Server
  # Deploy: docker compose -f /home/goug76/docker/docker-compose-dns.yml up -d
  # Remove: docker compose -f /home/goug76/docker/docker-compose-dns.yml down
  # Logs: docker compose -f /home/goug76/docker/docker-compose-dns.yml logs <container name>

  # Portainer
  - compose/dns/portainer.yml

  # Database
  - compose/dns/mysql.yml
  - compose/dns/phpmyadmin.yml
  - compose/dns/postgres.yml
  - compose/dns/adminer.yml

  # Reverse Proxy Manager
  - compose/dns/npm.yml

  # Adblocking DNS
  - compose/dns/adguardhome.yml
  - compose/dns/unbound.yml
  - compose/dns/cloudflare-ddns.yml

  # Ansible Semaphore
  - compose/dns/semaphore.yml

  # Password Manager  
  - compose/dns/vaultwarden.yml

  # Dashboard
  - compose/glances.yml