networks:
  rpi4b-network:
    name: rpi4b-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  mysql-network:
    driver: bridge
    name: mysql-network
    ipam:
      config:
        - subnet: 172.21.0.0/24

include:
  # PREFIX dns = DNS / AdBlock Server
  # Deploy: docker compose -f /home/goug76/docker/docker-compose-dns.yml up -d
  # Remove: docker compose -f /home/goug76/docker/docker-compose-dns.yml down
  # Logs: docker compose -f /home/goug76/docker/docker-compose-dns.yml logs <container name>

  # Reverse Proxy Manager
  - compose/npm.yml

  # Portainer Agent
  - compose/portainer-agent.yml

  # Adblocking
  - compose/dns/adguardhome.yml

  # DNS Resolver
  - compose/dns/unbound.yml

  # DDNS 
  - compose/dns/cloudflare-ddns.yml

  # Database
  - compose/dns/mysql.yml
  - compose/dns/phpmyadmin.yml

  # Ansible  
  - compose/dns/semaphore.yml