networks:
  rpi4b-network:
    name: rpi4b-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  mysql-network:
    driver: bridge
    name: mysql-network
    ipam:
      config:
        - subnet: 172.21.0.0/24

include:
  # PREFIX dns = DNS / AdBlock Server

  # Portainer Agent
  - compose/portainer-agent.yml

  # Adblocking
  - compose/dns/adguardhome.yml

  # DNS Resolver
  - compose/dns/unbound.yml

  # DDNS 
  - compose/dns/cloudflare-ddns.yml

  # Database
  - compose/dns/mysql.yml
  - compose/dns/phpmyadmin.yml

  # Ansible  
  - compose/dns/semaphore.yml