networks:
  rpi4b-network:
    name: rpi4b-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  database-network:
    driver: bridge
    name: database-network

include:
  # PREFIX dns = DNS / AdBlock Server
  # Deploy: docker compose -f /home/goug76/docker/docker-compose-dns.yml up -d
  # Remove: docker compose -f /home/goug76/docker/docker-compose-dns.yml down
  # Logs:   docker compose -f /home/goug76/docker/docker-compose-dns.yml logs <container name>
  # Update: docker compose -f /home/goug76/docker/docker-compose-dns.yml pull
  #         docker compose -f /home/goug76/docker/docker-compose-dns.yml up --force-recreate -d

  # Portainer
  - compose/dns/portainer.yml

  # Adblocking DNS
  - compose/dns/adguardhome.yml
  - compose/dns/unbound.yml
  - compose/dns/cloudflare-ddns.yml

  # Certificate Authority
  - compose/dns/step-ca.yml

  # Reverse Proxy Manager
  - compose/dns/npm.yml

  # VPN
  - compose/dns/wireguard.yml

  # Database
  - compose/postgres.yml
  - compose/dns/pgadmin.yml

  # Ansible Semaphore
  - compose/dns/semaphore.yml

  # Password Manager SSO
  - compose/dns/vaultwarden.yml

  # Dashboard
  - compose/glances.yml