networks:
  rpi4b-network:
    name: rpi4b-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  mysql-network:
    driver: bridge
    name: mysql-network
    ipam:
      config:
        - subnet: 172.21.0.0/24

include:
  # PREFIX dns = DNS / AdBlock Server

  # Adblocking
  - compose/$HOSTNAME/adguardhome.yml

  # DNS Resolver
  - compose/$HOSTNAME/unbound.yml

  # DDNS 
  - compose/$HOSTNAME/cloudflare-ddns.yml

  # Database
  - compose/$HOSTNAME/mysql.yml
  - compose/$HOSTNAME/phpmyadmin.yml