networks:
  rpi4b-network:
    name: rpi4b-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  mysql-network:
    driver: bridge
    name: mysql-network
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  base:
    env_file:
      - .env
      - .dns.env

include:
  # PREFIX dns = DNS / AdBlock Server

  # Adblocking
  - compose/dns/adguardhome.yml

  # DNS Resolver
  - compose/dns/unbound.yml

  # DDNS 
  - compose/dns/cloudflare-ddns.yml

  # Database
  - compose/dns/mysql.yml
  - compose/dns/phpmyadmin.yml

  # Ansible  
  - compose/dns/semaphore.yml