networks:
  rpi4b-network:
    name: rpi4b-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  default:
    driver: bridge

include:
  # PREFIX dns = DNS / AdBlock Server

  # Adblocking
  - compose/$HOSTNAME/adguardhome.yml

  # DNS Resolver
  - compose/$HOSTNAME/unbound.yml

  # DDNS 
  - compose/$HOSTNAME/cloudflare-ddns.yml