networks:
  default:
    driver: bridge

include:
  # PREFIX prod = Production Docker Server
  # Deploy: docker compose -f /home/goug76/docker/docker-compose-prod.yml up -d
  # Remove: docker compose -f /home/goug76/docker/docker-compose-prod.yml down
  # Logs: docker compose -f /home/goug76/docker/docker-compose-prod.yml logs <container name>

  # CORE
  - compose/portainer-agent.yml

  # Monitoring
  - compose/glances.yml

  # Dashboard
  - compose/prod/dashy.yml