services:
  vpn:
    container_name: vpn
    image: ghcr.io/goug76/nordvpn:latest
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=${TOKEN}
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=${NETWORK}  # So it can be accessed within the local network
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only