# https://github.com/linuxserver/docker-plex
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - /mnt/media:/media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker