services:
  adguardhome: 
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp # DNS
      - 53:53/udp
      - 784:784/udp # DNS over QUIC
      - 853:853/tcp # DNS over TLS
      - 3000:3000/tcp # initial installation
      - 8080:80/tcp # Dashboard
      - 4443:443/tcp # DNS over HTTPs
    volumes:
      - $DOCKERDIR/appdata/adguardhome/work:/opt/adguardhome/work
      - $DOCKERDIR/appdata/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - rpi4b