services:
  adminer:
    container_name: adminer
    image: adminer
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      TZ: '${TZ}'
    networks:
      - database-network