services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - $DOCKERDIR/appdata/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped