services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql
    security_opt:
      - no-new-privileges:true
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - $DOCKERDIR/appdata/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      TZ: '${TZ}'
    networks:
      mysql-network:
        ipv4_address: 172.21.0.10 # fixed IP address