services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql
    security_opt:
      - no-new-privileges:true
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - $DOCKERDIR/appdata/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: '${USER}'
      MYSQL_PASSWORD: /run/secrets/mysql_pwd
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_pwd
      TZ: '${TZ}'
    secrets:
      - mysql_pwd
    networks:
      rpi4b-network:
        ipv4_address: 172.20.0.3 # fixed IP address