services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/npm/data:/data
      - $DOCKERDIR/appdata/npm/letsencrypt:/etc/letsencrypt
      - $DOCKERDIR/appdata/npm/98-themepark:/etc/cont-init.d/99-themepark
    networks:
      - rpi4b-network