services:
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    volumes:
    - $DOCKERDIR/appdata/unbound:/opt/unbound/etc/unbound
    restart: unless-stopped
    networks:
      - rpi4b