services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    image: klutchell/unbound
    environment:
      - TZ=$TZ
    networks:
      rpi4b-network:
        ipv4_address: 172.20.0.53 # fixed IP address