services:
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    network_mode: rpi4b
    volumes:
    - $DOCKERDIR/appdata/unbound:/opt/unbound/etc/unbound
    restart: unless-stopped