services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - '83:80'
    environment:
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=${PUSH_INSTALLATION_ID}
      - PUSH_INSTALLATION_KEY=${PUSH_INSTALLATION_KEY}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/vaultwarden/:/data/
    networks:
      rpi4b-network: