services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    ports:
      - '8080:80'
    volumes:
      - $DOCKERDIR/appdata/dashy/conf.yml:/app/public/conf.yml
      - $DOCKERDIR/appdata/dashy/icons:/app/public/item-icons/icons
    restart: unless-stopped