services:
  traefik:
    image: traefik:v2.11.2
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      traefik:
      socket_proxy:
    ports:
      - 80:80
      - 443:443
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKERDIR/appdata/traefik/rules:/rules
      - $DOCKERDIR/appdata/traefik/acme/acme.json:/acme.json
      - $DOCKERDIR/logs/traefik:/logs
      - $DOCKERDIR/appdata/traefik/traefik.yml:/traefik.yml:ro
    environment:
      - TZ=$TZ
      # - CF_API_EMAIL='${EMAIL}'
      - CF_DNS_API_TOKEN='${CF_DNS_API_TOKEN}'
      - TRAEFIK_USERS=$TRAEFIK_USERS
      - DOMAINNAME_1
      - DOMAINNAME_2
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.$DOMAINNAME_1`)"
      - "traefik.http.routers.dashboard.middlewares=auth"
      # Services - API
      - "traefik.http.routers.dashboard.service=api@internal"
      # Get Certificates
      - "traefik.http.routers.dashboard.tls.certresolver=cloudflare"
      - "traefik.http.routers.dashboard.tls.domains[0].main=goug.info"
      - "traefik.http.routers.dashboard.tls.domains[0].sans=*.goug.info"   
      # Middlewares
      - "traefik.http.middlewares.auth.basicauth.users=$TRAEFIK_USERS"